version: '3.7'
services:
  frontend:
    build: ./ui
    networks:
       - main
    ports:
      - 80:80
    depends_on:
      - web

  web:
    restart: always
    build: ./web
    command: deploy/start_web_server.sh
    networks:
      - main
    ports:
      - "8080:8080"
    depends_on:
      - worker
      - elasticsearch

  worker:
    build: ./web
    restart: always
    command: deploy/start_worker.sh
    depends_on:
      - redis
      - elasticsearch
    networks:
      - main

  redis:
    image: redis:latest
    restart: always
    hostname: redis
    networks:
      - main
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - main

  algos:
    build: ./algos
    restart: always
    depends_on:
      - redis
    networks:
      - main

volumes:
  data_web:

networks:
  main:
